version: '3.7'

services:
  backend:
    image: "156711951873.dkr.ecr.us-west-1.amazonaws.com/sg_decoding:backend"
    ports:
      - "2000:2000"
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://mongodb-app:27017/myapp"
    networks:
      - sgdecodenet
    depends_on: 
      - mongodb-app
    links:
      - mongodb-app
  mongodb-app:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:  
      - mongo:/data/db
    networks:
      - sgdecodenet

  frontend:
    image: "156711951873.dkr.ecr.us-west-1.amazonaws.com/sg_decoding:frontend"
    ports:
      - "3000:3000"
    networks:
      - sgdecodenet
  
networks:
  sgdecodenet:
    driver: bridge
volumes:
  mongo: 
  

