version: '3.7'

services:
  # network_mode: "host"  
  backend:
    # env_file:
    #     "./backend/backend.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "sgdecode_backend"
    # ports:
    #   - "2000:2000"
    networks:
      - sgdecodenet
    
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "sgdecode_frontend"
    # ports:
    #   - "80:80"
    links:
      - "backend:be"
    networks:
      - sgdecodenet
  
  revproxy:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./reverse_proxy
      dockerfile: ./Dockerfile
    image: "sgdecode_revproxy"
    networks: 
      - sgdecodenet
    ports: 
      - "80:80"

networks:
  sgdecodenet: